# This is a generated file. Not intended for manual editing.
services:
  webapi:
    build:
      context: "D:\\Git\\DriverInformationSystemBackend"
      dockerfile: "WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\Aldmi\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\Aldmi\\.nuget\\packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "dis_backend:dev"
    ports:
    - "127.0.0.1:57011:57100"
    - "127.0.0.1:57211:57300"
    volumes:
    - "C:\\Users\\Aldmi\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "D:\\Git\\DriverInformationSystemBackend\\WebApi:/app:rw"
    - "D:\\Git\\DriverInformationSystemBackend:/src:rw"
    - "C:\\Users\\Aldmi\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.1\\\
      Linux64:/riderDebugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2022.3.3/bin:/riderLogsConf"
    - "C:\\Users\\Aldmi\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_10_13_23_52_44:/riderLogs:rw"
    working_dir: "/app"
